# Generated by Django 3.1.7 on 2021-04-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=10)),
                ('year_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('food_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('submit_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.staff')),
                ('access_level', models.IntegerField()),
            ],
            bases=('api.staff',),
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.staff')),
                ('position', models.CharField(max_length=50)),
            ],
            bases=('api.staff',),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.staff')),
                ('specialization', models.CharField(max_length=50)),
            ],
            bases=('api.staff',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=10)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building')),
                ('student_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Resolves',
            fields=[
                ('resolves_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_resolved', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('urgency_rating', models.IntegerField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maintenancerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_recieved', models.DateField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='api.room'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.CreateModel(
            name='Fulfills',
            fields=[
                ('fulfills_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_fulfilled', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('food_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodorder')),
            ],
        ),
        migrations.AddField(
            model_name='foodorder',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('problem_description', models.CharField(max_length=200)),
                ('resolution_description', models.CharField(max_length=200)),
                ('urgency_rating', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building_id', 'room_no'), name='room_constraint'),
        ),
        migrations.AddField(
            model_name='resolves',
            name='technician_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.technician'),
        ),
        migrations.AddField(
            model_name='fulfills',
            name='chef_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chef'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.admin'),
        ),
        migrations.AddConstraint(
            model_name='resolves',
            constraint=models.UniqueConstraint(fields=('technician_id', 'request_id'), name='resolves_constraint'),
        ),
        migrations.AddConstraint(
            model_name='fulfills',
            constraint=models.UniqueConstraint(fields=('chef_id', 'food_order_id'), name='fulfills_constraint'),
        ),
    ]
