# Generated by Django 3.1.7 on 2021-04-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_time_resolved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date_time_resolved',
            field=models.DateTimeField(null=True),
        ),
    ]
