# Generated by Django 3.1.7 on 2021-04-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='department',
        ),
        migrations.AddField(
            model_name='admin',
            name='access_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MID', 'MID'), ('HIGH', 'HIGH')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='chef',
            name='position',
            field=models.CharField(choices=[('LINE', 'LINE'), ('SOUS', 'SOUS'), ('HEAD', 'HEAD')], default='LINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='technician',
            name='specialization',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('HEATING', 'HEATING'), ('PLUMBING', 'PLUMBING')], default='GENERAL', max_length=50),
        ),
    ]
