# Generated by Django 3.1.7 on 2021-04-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210412_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolution_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
