# Generated by Django 3.1.7 on 2021-04-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210408_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='date_time_fulfilled',
            field=models.DateTimeField(null=True),
        ),
    ]
