# Generated by Django 3.1.7 on 2021-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210414_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_time_resolved',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='submit_date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='date_time_fulfilled',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='submit_date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date_time_resolved',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='submit_date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
